/* This file was generated by the Hex-Rays decompiler version 9.3.0.260327.
   Copyright (c) 2007-2025 Hex-Rays <info@hex-rays.com>

   Detected compiler: GNU C++
*/

#include <defs.h>


//-------------------------------------------------------------------------
// Function declarations

void *init_proc();
void sub_1030();
void sub_1040();
void sub_1050();
void sub_1060();
void sub_1070();
void sub_1080();
void sub_1090();
void sub_10A0();
void sub_10B0();
void sub_10C0();
void sub_10D0();
void sub_10E0();
void sub_10F0();
void sub_1100();
void sub_1110();
void sub_1120();
void sub_1130();
void sub_1140();
void sub_1150();
void sub_1160();
void sub_1170();
void sub_1180();
void sub_1190();
void sub_11A0();
void sub_11B0();
void sub_11C0();
void sub_11D0();
// int __usercall sub_11E0@<eax>(int a1@<ebx>);
// int fflush(FILE *stream);
// int inet_pton(int af, const char *cp, void *buf);
// char *fgets(char *s, int n, FILE *stream);
// __sighandler_t signal(int sig, __sighandler_t handler);
// unsigned int sleep(unsigned int seconds);
// unsigned int alarm(unsigned int seconds);
// FILE *popen(const char *command, const char *modes);
// char *strtok_r(char *s, const char *delim, char **save_ptr);
// char *getenv(const char *name);
// int puts(const char *s);
// void exit(int status);
// int pclose(FILE *stream);
// int __libc_start_main(int (*main)(int, char **, char **), int argc, char **ubp_av, void (*init)(), void (*fini)(), void (*rtld_fini)(), void *stack_end);
// int __isoc99_sscanf(_DWORD, const char *, ...); weak
// FILE *fopen(const char *filename, const char *modes);
// int putchar(int c);
// int __cdecl __printf_chk(_DWORD, _DWORD);
// int socket(int domain, int type, int protocol);
// int __fprintf_chk(_DWORD, _DWORD, const char *, ...); weak
// int strtol(const char *nptr, char **endptr, int base);
// int connect(int fd, const struct sockaddr *addr, socklen_t len);
// int close(int fd);
// const unsigned __int16 **__ctype_b_loc(void);
// int __cdecl __sprintf_chk(_DWORD, _DWORD, _DWORD, _DWORD, _DWORD); weak
// void __usercall __noreturn start(int a1@<eax>, void (*a2)()@<edx>);
void sub_13C6();
void _x86_get_pc_thunk_bx();
char *deregister_tm_clones();
int register_tm_clones();
char *_do_global_dtors_aux();
int frame_dummy();
void _x86_get_pc_thunk_dx();
int __cdecl main(int argc, const char **argv, const char **envp);
bool __cdecl shigatsu_wa_kimi_no_uso(const char *a1);
int __cdecl gurren_lagann(char *nptr); // idb
unsigned int __cdecl cruel_angel_thesis(int a1);
unsigned int __cdecl one_piece(int a1);
unsigned int __cdecl Geometric_Dance(int a1);
unsigned int __cdecl crossing_field(const char *a1);
unsigned int __cdecl renai_circulation(int a1);
unsigned int __cdecl kira_game(const char *a1);
int __cdecl Shougaizettaisouaisengen(unsigned __int8 *a1);
unsigned int __cdecl Ruler_Count_Zero_2(_BYTE *a1);
void *_x86_get_pc_thunk_ax();
void __noreturn sig_handler(); // weak
void __cdecl __noreturn invalid_phase(int a1);
int __cdecl string_length(_BYTE *a1);
int __cdecl strings_not_equal(char *a1, _BYTE *a2);
int __cdecl yakiniku(int a1, int a2);
int __cdecl sukiyaki(char a1);
int __cdecl karaage(int a1);
int __cdecl ramen(int a1, char a2);
int __cdecl ruler_count_zero(int a1, int a2);
int __cdecl english_or_spanish(int a1);
int __cdecl red_catastrophe(unsigned __int8 *a1, int a2);
unsigned int start_game();
void start_game_solve();
int __cdecl blank_line(char *a1);
char *skip();
unsigned int __cdecl send_msg();
void __noreturn trap();
int __cdecl read_six_numbers(int a1, int a2);
char *__cdecl read_n_numbers(char *s, int a2, int a3);
int __cdecl input_to_integer(int a1, int a2);
const char *read_line();
int stage_completed();
void _x86_get_pc_thunk_bp();
void __noreturn sigalrm_handler(); // weak
int __cdecl submitr(int a1, int a2, const char *a3, const char *a4, const char *a5, const char *a6, int a7);
unsigned int __cdecl init_timeout(int a1);
int __cdecl init_driver(char *a1);
int __cdecl driver_post(const char *a1, const char *a2, int a3, char *a4);
int _libc_csu_init();
void _libc_csu_fini();
void term_proc();
// int _cxa_finalize(void *);

//-------------------------------------------------------------------------
// Data declarations

int dword_0 = 1179403647; // weak
// extern _UNKNOWN __snprintf_chk; weak
_UNKNOWN unk_4050; // weak
char byte_4E48[1280] =
{
  '\xE2',
  '\x95',
  '\x94',
  '\xE2',
  '\x95',
  '\x90',
  '\xE2',
  '\x95',
  '\x90',
  '\xE2',
  '\x95',
  '\x90',
  '\xE2',
  '\x95',
  '\x90',
  '\xE2',
  '\x95',
  '\x90',
  '\xE2',
  '\x95',
  '\x90',
  '\xE2',
  '\x95',
  '\x90',
  '\xE2',
  '\x95',
  '\x90',
  '\xE2',
  '\x95',
  '\x90',
  '\xE2',
  '\x95',
  '\x90',
  '\xE2',
  '\x95',
  '\x90',
  '\xE2',
  '\x95',
  '\x90',
  '\xE2',
  '\x95',
  '\x90',
  '\xE2',
  '\x95',
  '\x90',
  '\xE2',
  '\x95',
  '\x90',
  '\xE2',
  '\x95',
  '\x90',
  '\xE2',
  '\x95',
  '\x90',
  '\xE2',
  '\x95',
  '\x90',
  '\xE2',
  '\x95',
  '\x90',
  '\xE2',
  '\x95',
  '\x90',
  '\xE2',
  '\x95',
  '\x90',
  '\xE2',
  '\x95',
  '\x90',
  '\xE2',
  '\x95',
  '\x90',
  '\xE2',
  '\x95',
  '\x90',
  '\xE2',
  '\x95',
  '\x90',
  '\xE2',
  '\x95',
  '\x90',
  '\xE2',
  '\x95',
  '\x90',
  '\xE2',
  '\x95',
  '\x90',
  '\xE2',
  '\x95',
  '\x90',
  '\xE2',
  '\x95',
  '\x90',
  '\xE2',
  '\x95',
  '\x90',
  '\xE2',
  '\x95',
  '\x90',
  '\xE2',
  '\x95',
  '\x90',
  '\xE2',
  '\x95',
  '\x90',
  '\xE2',
  '\x95',
  '\x90',
  '\xE2',
  '\x95',
  '\x90',
  '\xE2',
  '\x95',
  '\x90',
  '\xE2',
  '\x95',
  '\x90',
  '\xE2',
  '\x95',
  '\x90',
  '\xE2',
  '\x95',
  '\x90',
  '\xE2',
  '\x95',
  '\x90',
  '\xE2',
  '\x95',
  '\x90',
  '\xE2',
  '\x95',
  '\x90',
  '\xE2',
  '\x95',
  '\x90',
  '\xE2',
  '\x95',
  '\x90',
  '\xE2',
  '\x95',
  '\x90',
  '\xE2',
  '\x95',
  '\x90',
  '\xE2',
  '\x95',
  '\x90',
  '\xE2',
  '\x95',
  '\x90',
  '\xE2',
  '\x95',
  '\x90',
  '\xE2',
  '\x95',
  '\x90',
  '\xE2',
  '\x95',
  '\x90',
  '\xE2',
  '\x95',
  '\x90',
  '\xE2',
  '\x95',
  '\x90',
  '\xE2',
  '\x95',
  '\x90',
  '\xE2',
  '\x95',
  '\x90',
  '\xE2',
  '\x95',
  '\x90',
  '\xE2',
  '\x95',
  '\x90',
  '\xE2',
  '\x95',
  '\x90',
  '\xE2',
  '\x95',
  '\x90',
  '\xE2',
  '\x95',
  '\x90',
  '\xE2',
  '\x95',
  '\x90',
  '\xE2',
  '\x95',
  '\x90',
  '\xE2',
  '\x95',
  '\x90',
  '\xE2',
  '\x95',
  '\x97',
  '\n',
  '\xE2',
  '\x95',
  '\x91',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  '\xE2',
  '\x95',
  '\x91',
  '\n',
  '\xE2',
  '\x95',
  '\x91',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  'C',
  'O',
  'R',
  'E',
  ' ',
  'C',
  'H',
  'A',
  'L',
  'L',
  'E',
  'N',
  'G',
  'E',
  'S',
  ' ',
  'C',
  'O',
  'M',
  'P',
  'L',
  'E',
  'T',
  'E',
  'D',
  '!',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  '\xE2',
  '\x95',
  '\x91',
  '\n',
  '\xE2',
  '\x95',
  '\x91',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  '\xE2',
  '\x95',
  '\x91',
  '\n',
  '\xE2',
  '\x95',
  '\x91',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  'Y',
  'o',
  'u',
  '\'',
  'v',
  'e',
  ' ',
  'p',
  'r',
  'o',
  'v',
  'e',
  'n',
  ' ',
  'y',
  'o',
  'u',
  'r',
  's',
  'e',
  'l',
  'f',
  '.',
  ' ',
  'Y',
  'o',
  'u',
  '\'',
  'v',
  'e',
  ' ',
  'e',
  'a',
  'r',
  'n',
  'e',
  'd',
  ' ',
  'y',
  'o',
  'u',
  'r',
  ' ',
  'p',
  'l',
  'a',
  'c',
  'e',
  '.',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  '\xE2',
  '\x95',
  '\x91',
  '\n',
  '\xE2',
  '\x95',
  '\x91',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  '\xE2',
  '\x95',
  '\x91',
  '\n',
  '\xE2',
  '\x95',
  '\x9A',
  '\xE2',
  '\x95',
  '\x90',
  '\xE2',
  '\x95',
  '\x90',
  '\xE2',
  '\x95',
  '\x90',
  '\xE2',
  '\x95',
  '\x90',
  '\xE2',
  '\x95',
  '\x90',
  '\xE2',
  '\x95',
  '\x90',
  '\xE2',
  '\x95',
  '\x90',
  '\xE2',
  '\x95',
  '\x90',
  '\xE2',
  '\x95',
  '\x90',
  '\xE2',
  '\x95',
  '\x90',
  '\xE2',
  '\x95',
  '\x90',
  '\xE2',
  '\x95',
  '\x90',
  '\xE2',
  '\x95',
  '\x90',
  '\xE2',
  '\x95',
  '\x90',
  '\xE2',
  '\x95',
  '\x90',
  '\xE2',
  '\x95',
  '\x90',
  '\xE2',
  '\x95',
  '\x90',
  '\xE2',
  '\x95',
  '\x90',
  '\xE2',
  '\x95',
  '\x90',
  '\xE2',
  '\x95',
  '\x90',
  '\xE2',
  '\x95',
  '\x90',
  '\xE2',
  '\x95',
  '\x90',
  '\xE2',
  '\x95',
  '\x90',
  '\xE2',
  '\x95',
  '\x90',
  '\xE2',
  '\x95',
  '\x90',
  '\xE2',
  '\x95',
  '\x90',
  '\xE2',
  '\x95',
  '\x90',
  '\xE2',
  '\x95',
  '\x90',
  '\xE2',
  '\x95',
  '\x90',
  '\xE2',
  '\x95',
  '\x90',
  '\xE2',
  '\x95',
  '\x90',
  '\xE2',
  '\x95',
  '\x90',
  '\xE2',
  '\x95',
  '\x90',
  '\xE2',
  '\x95',
  '\x90',
  '\xE2',
  '\x95',
  '\x90',
  '\xE2',
  '\x95',
  '\x90',
  '\xE2',
  '\x95',
  '\x90',
  '\xE2',
  '\x95',
  '\x90',
  '\xE2',
  '\x95',
  '\x90',
  '\xE2',
  '\x95',
  '\x90',
  '\xE2',
  '\x95',
  '\x90',
  '\xE2',
  '\x95',
  '\x90',
  '\xE2',
  '\x95',
  '\x90',
  '\xE2',
  '\x95',
  '\x90',
  '\xE2',
  '\x95',
  '\x90',
  '\xE2',
  '\x95',
  '\x90',
  '\xE2',
  '\x95',
  '\x90',
  '\xE2',
  '\x95',
  '\x90',
  '\xE2',
  '\x95',
  '\x90',
  '\xE2',
  '\x95',
  '\x90',
  '\xE2',
  '\x95',
  '\x90',
  '\xE2',
  '\x95',
  '\x90',
  '\xE2',
  '\x95',
  '\x90',
  '\xE2',
  '\x95',
  '\x90',
  '\xE2',
  '\x95',
  '\x90',
  '\xE2',
  '\x95',
  '\x90',
  '\xE2',
  '\x95',
  '\x90',
  '\xE2',
  '\x95',
  '\x90',
  '\xE2',
  '\x95',
  '\x90',
  '\xE2',
  '\x95',
  '\x90',
  '\xE2',
  '\x95',
  '\x90',
  '\xE2',
  '\x95',
  '\x90',
  '\xE2',
  '\x95',
  '\x90',
  '\xE2',
  '\x95',
  '\x90',
  '\xE2',
  '\x95',
  '\x9D',
  '\n',
  '\n',
  '\"',
  'Y',
  'o',
  'u',
  ' ',
  'd',
  'i',
  'd',
  ' ',
  'i',
  't',
  '.',
  ' ',
  'Y',
  'o',
  'u',
  ' ',
  'a',
  'c',
  't',
  'u',
  'a',
  'l',
  'l',
  'y',
  ' ',
  'm',
  'a',
  'd',
  'e',
  ' ',
  'i',
  't',
  ' ',
  't',
  'h',
  'r',
  'o',
  'u',
  'g',
  'h',
  ' ',
  'a',
  'l',
  'l',
  ' ',
  's',
  'e',
  'v',
  'e',
  'n',
  ' ',
  'g',
  'a',
  't',
  'e',
  's',
  '.',
  '\"',
  '\n',
  '\"',
  'W',
  'e',
  '.',
  '.',
  '.',
  ' ',
  'w',
  'e',
  ' ',
  'h',
  'o',
  'n',
  'e',
  's',
  't',
  'l',
  'y',
  ' ',
  'd',
  'i',
  'd',
  'n',
  '\'',
  't',
  ' ',
  't',
  'h',
  'i',
  'n',
  'k',
  ' ',
  'y',
  'o',
  'u',
  '\'',
  'd',
  ' ',
  'g',
  'e',
  't',
  ' ',
  't',
  'h',
  'i',
  's',
  ' ',
  'f',
  'a',
  'r',
  '.',
  '\"',
  '\n',
  '\"',
  'B',
  'u',
  't',
  ' ',
  't',
  'h',
  'e',
  'r',
  'e',
  '\'',
  's',
  ' ',
  's',
  'o',
  'm',
  'e',
  't',
  'h',
  'i',
  'n',
  'g',
  ' ',
  'm',
  'o',
  'r',
  'e',
  '.',
  ' ',
  'S',
  'o',
  'm',
  'e',
  't',
  'h',
  'i',
  'n',
  'g',
  ' ',
  'f',
  'o',
  'r',
  ' ',
  't',
  'h',
  'o',
  's',
  'e',
  ' ',
  'b',
  'r',
  'a',
  'v',
  'e',
  ' ',
  'e',
  'n',
  'o',
  'u',
  'g',
  'h',
  ' ',
  't',
  'o',
  ' ',
  'k',
  'e',
  'e',
  'p',
  ' ',
  'g',
  'o',
  'i',
  'n',
  'g',
  '.',
  '\"',
  '\n',
  '\n',
  '\"',
  'T',
  'h',
  'r',
  'e',
  'e',
  ' ',
  'f',
  'i',
  'n',
  'a',
  'l',
  ' ',
  't',
  'r',
  'i',
  'a',
  'l',
  's',
  ' ',
  'a',
  'w',
  'a',
  'i',
  't',
  '.',
  ' ',
  'T',
  'h',
  'e',
  'y',
  '\'',
  'r',
  'e',
  ' ',
  'n',
  'o',
  't',
  ' ',
  'r',
  'e',
  'q',
  'u',
  'i',
  'r',
  'e',
  'd',
  '.',
  ' ',
  'Y',
  'o',
  'u',
  '\'',
  'v',
  'e',
  ' ',
  'a',
  'l',
  'r',
  'e',
  'a',
  'd',
  'y',
  ' ',
  'p',
  'r',
  'o',
  'v',
  'e',
  'n',
  ' ',
  'e',
  'v',
  'e',
  'r',
  'y',
  't',
  'h',
  'i',
  'n',
  'g',
  '.',
  '\"',
  '\n',
  '\"',
  'B',
  'u',
  't',
  ' ',
  'i',
  'f',
  ' ',
  'y',
  'o',
  'u',
  ' ',
  'w',
  'a',
  'n',
  't',
  ' ',
  't',
  'o',
  ' ',
  'g',
  'o',
  ' ',
  'd',
  'e',
  'e',
  'p',
  'e',
  'r',
  '?',
  ' ',
  'T',
  'o',
  ' ',
  't',
  'r',
  'u',
  'l',
  'y',
  ' ',
  'u',
  'n',
  'd',
  'e',
  'r',
  's',
  't',
  'a',
  'n',
  'd',
  '?',
  ' ',
  'T',
  'o',
  ' ',
  'u',
  'n',
  'l',
  'o',
  'c',
  'k',
  ' ',
  't',
  'h',
  'e',
  ' ',
  'f',
  'i',
  'n',
  'a',
  'l',
  ' ',
  's',
  'e',
  'c',
  'r',
  'e',
  't',
  's',
  '?',
  '\"',
  '\n',
  '\"',
  'W',
  'e',
  '\'',
  'r',
  'e',
  ' ',
  'h',
  'e',
  'r',
  'e',
  '.',
  ' ',
  'W',
  'a',
  'i',
  't',
  'i',
  'n',
  'g',
  '.',
  ' ',
  'W',
  'e',
  ' ',
  'a',
  'l',
  'w',
  'a',
  'y',
  's',
  ' ',
  'h',
  'a',
  'v',
  'e',
  ' ',
  'b',
  'e',
  'e',
  'n',
  '.',
  '\"',
  '\n',
  '\n',
  '\"',
  'A',
  'r',
  'e',
  ' ',
  'y',
  'o',
  'u',
  ' ',
  'r',
  'e',
  'a',
  'd',
  'y',
  ' ',
  't',
  'o',
  ' ',
  'p',
  'u',
  's',
  'h',
  ' ',
  'b',
  'e',
  'y',
  'o',
  'n',
  'd',
  '?',
  ' ',
  'O',
  'r',
  ' ',
  'd',
  'o',
  ' ',
  'y',
  'o',
  'u',
  ' ',
  'w',
  'a',
  'n',
  't',
  ' ',
  't',
  'o',
  ' ',
  'r',
  'e',
  's',
  't',
  ' ',
  'h',
  'e',
  'r',
  'e',
  ',',
  ' ',
  'k',
  'n',
  'o',
  'w',
  'i',
  'n',
  'g',
  ' ',
  'y',
  'o',
  'u',
  '\'',
  'v',
  'e',
  ' ',
  'w',
  'o',
  'n',
  '?',
  '\"',
  '\n',
  '\"',
  'E',
  'i',
  't',
  'h',
  'e',
  'r',
  ' ',
  'c',
  'h',
  'o',
  'i',
  'c',
  'e',
  '.',
  '.',
  '.',
  ' ',
  'w',
  'e',
  '\'',
  'r',
  'e',
  ' ',
  'p',
  'r',
  'o',
  'u',
  'd',
  ' ',
  'o',
  'f',
  ' ',
  'y',
  'o',
  'u',
  '.',
  '\"',
  '\n',
  '\0',
  '\0',
  '\0',
  '\0'
}; // weak
char byte_59AC[684] =
{
  '\xE2',
  '\x95',
  '\x94',
  '\xE2',
  '\x95',
  '\x90',
  '\xE2',
  '\x95',
  '\x90',
  '\xE2',
  '\x95',
  '\x90',
  '\xE2',
  '\x95',
  '\x90',
  '\xE2',
  '\x95',
  '\x90',
  '\xE2',
  '\x95',
  '\x90',
  '\xE2',
  '\x95',
  '\x90',
  '\xE2',
  '\x95',
  '\x90',
  '\xE2',
  '\x95',
  '\x90',
  '\xE2',
  '\x95',
  '\x90',
  '\xE2',
  '\x95',
  '\x90',
  '\xE2',
  '\x95',
  '\x90',
  '\xE2',
  '\x95',
  '\x90',
  '\xE2',
  '\x95',
  '\x90',
  '\xE2',
  '\x95',
  '\x90',
  '\xE2',
  '\x95',
  '\x90',
  '\xE2',
  '\x95',
  '\x90',
  '\xE2',
  '\x95',
  '\x90',
  '\xE2',
  '\x95',
  '\x90',
  '\xE2',
  '\x95',
  '\x90',
  '\xE2',
  '\x95',
  '\x90',
  '\xE2',
  '\x95',
  '\x90',
  '\xE2',
  '\x95',
  '\x90',
  '\xE2',
  '\x95',
  '\x90',
  '\xE2',
  '\x95',
  '\x90',
  '\xE2',
  '\x95',
  '\x90',
  '\xE2',
  '\x95',
  '\x90',
  '\xE2',
  '\x95',
  '\x90',
  '\xE2',
  '\x95',
  '\x90',
  '\xE2',
  '\x95',
  '\x90',
  '\xE2',
  '\x95',
  '\x90',
  '\xE2',
  '\x95',
  '\x90',
  '\xE2',
  '\x95',
  '\x90',
  '\xE2',
  '\x95',
  '\x90',
  '\xE2',
  '\x95',
  '\x90',
  '\xE2',
  '\x95',
  '\x90',
  '\xE2',
  '\x95',
  '\x90',
  '\xE2',
  '\x95',
  '\x90',
  '\xE2',
  '\x95',
  '\x90',
  '\xE2',
  '\x95',
  '\x90',
  '\xE2',
  '\x95',
  '\x90',
  '\xE2',
  '\x95',
  '\x90',
  '\xE2',
  '\x95',
  '\x90',
  '\xE2',
  '\x95',
  '\x90',
  '\xE2',
  '\x95',
  '\x90',
  '\xE2',
  '\x95',
  '\x90',
  '\xE2',
  '\x95',
  '\x90',
  '\xE2',
  '\x95',
  '\x90',
  '\xE2',
  '\x95',
  '\x90',
  '\xE2',
  '\x95',
  '\x90',
  '\xE2',
  '\x95',
  '\x90',
  '\xE2',
  '\x95',
  '\x90',
  '\xE2',
  '\x95',
  '\x90',
  '\xE2',
  '\x95',
  '\x90',
  '\xE2',
  '\x95',
  '\x90',
  '\xE2',
  '\x95',
  '\x90',
  '\xE2',
  '\x95',
  '\x90',
  '\xE2',
  '\x95',
  '\x90',
  '\xE2',
  '\x95',
  '\x90',
  '\xE2',
  '\x95',
  '\x90',
  '\xE2',
  '\x95',
  '\x90',
  '\xE2',
  '\x95',
  '\x90',
  '\xE2',
  '\x95',
  '\x90',
  '\xE2',
  '\x95',
  '\x90',
  '\xE2',
  '\x95',
  '\x97',
  '\n',
  '\xE2',
  '\x95',
  '\x91',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  '\xE2',
  '\x95',
  '\x91',
  '\n',
  '\xE2',
  '\x95',
  '\x91',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  'Y',
  'O',
  'U',
  ' ',
  'H',
  'A',
  'V',
  'E',
  ' ',
  'C',
  'O',
  'M',
  'P',
  'L',
  'E',
  'T',
  'E',
  'D',
  ' ',
  'T',
  'H',
  'E',
  ' ',
  'P',
  'R',
  'A',
  'K',
  'T',
  'I',
  'K',
  'U',
  'M',
  ' ',
  '2',
  ' ',
  'O',
  'D',
  'Y',
  'S',
  'S',
  'E',
  'Y',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  '\xE2',
  '\x95',
  '\x91',
  '\n',
  '\xE2',
  '\x95',
  '\x91',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  'A',
  'L',
  'L',
  ' ',
  'T',
  'R',
  'I',
  'A',
  'L',
  'S',
  ' ',
  'C',
  'O',
  'N',
  'Q',
  'U',
  'E',
  'R',
  'E',
  'D',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  '\xE2',
  '\x95',
  '\x91',
  '\n',
  '\xE2',
  '\x95',
  '\x91',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  '\xE2',
  '\x95',
  '\x91',
  '\n',
  '\xE2',
  '\x95',
  '\x9A',
  '\xE2',
  '\x95',
  '\x90',
  '\xE2',
  '\x95',
  '\x90',
  '\xE2',
  '\x95',
  '\x90',
  '\xE2',
  '\x95',
  '\x90',
  '\xE2',
  '\x95',
  '\x90',
  '\xE2',
  '\x95',
  '\x90',
  '\xE2',
  '\x95',
  '\x90',
  '\xE2',
  '\x95',
  '\x90',
  '\xE2',
  '\x95',
  '\x90',
  '\xE2',
  '\x95',
  '\x90',
  '\xE2',
  '\x95',
  '\x90',
  '\xE2',
  '\x95',
  '\x90',
  '\xE2',
  '\x95',
  '\x90',
  '\xE2',
  '\x95',
  '\x90',
  '\xE2',
  '\x95',
  '\x90',
  '\xE2',
  '\x95',
  '\x90',
  '\xE2',
  '\x95',
  '\x90',
  '\xE2',
  '\x95',
  '\x90',
  '\xE2',
  '\x95',
  '\x90',
  '\xE2',
  '\x95',
  '\x90',
  '\xE2',
  '\x95',
  '\x90',
  '\xE2',
  '\x95',
  '\x90',
  '\xE2',
  '\x95',
  '\x90',
  '\xE2',
  '\x95',
  '\x90',
  '\xE2',
  '\x95',
  '\x90',
  '\xE2',
  '\x95',
  '\x90',
  '\xE2',
  '\x95',
  '\x90',
  '\xE2',
  '\x95',
  '\x90',
  '\xE2',
  '\x95',
  '\x90',
  '\xE2',
  '\x95',
  '\x90',
  '\xE2',
  '\x95',
  '\x90',
  '\xE2',
  '\x95',
  '\x90',
  '\xE2',
  '\x95',
  '\x90',
  '\xE2',
  '\x95',
  '\x90',
  '\xE2',
  '\x95',
  '\x90',
  '\xE2',
  '\x95',
  '\x90',
  '\xE2',
  '\x95',
  '\x90',
  '\xE2',
  '\x95',
  '\x90',
  '\xE2',
  '\x95',
  '\x90',
  '\xE2',
  '\x95',
  '\x90',
  '\xE2',
  '\x95',
  '\x90',
  '\xE2',
  '\x95',
  '\x90',
  '\xE2',
  '\x95',
  '\x90',
  '\xE2',
  '\x95',
  '\x90',
  '\xE2',
  '\x95',
  '\x90',
  '\xE2',
  '\x95',
  '\x90',
  '\xE2',
  '\x95',
  '\x90',
  '\xE2',
  '\x95',
  '\x90',
  '\xE2',
  '\x95',
  '\x90',
  '\xE2',
  '\x95',
  '\x90',
  '\xE2',
  '\x95',
  '\x90',
  '\xE2',
  '\x95',
  '\x90',
  '\xE2',
  '\x95',
  '\x90',
  '\xE2',
  '\x95',
  '\x90',
  '\xE2',
  '\x95',
  '\x90',
  '\xE2',
  '\x95',
  '\x90',
  '\xE2',
  '\x95',
  '\x90',
  '\xE2',
  '\x95',
  '\x90',
  '\xE2',
  '\x95',
  '\x90',
  '\xE2',
  '\x95',
  '\x90',
  '\xE2',
  '\x95',
  '\x90',
  '\xE2',
  '\x95',
  '\x90',
  '\xE2',
  '\x95',
  '\x90',
  '\xE2',
  '\x95',
  '\x90',
  '\xE2',
  '\x95',
  '\x9D',
  '\n',
  '\0',
  '\0'
}; // weak
const char aThankYouThankY[] = "\"Thank you. Thank you for not giving up on us. On yourself.\"\n\"You pushed past every limit. You conquered even the impossible.\"\n\"You are the legend we always knew you could be. The one we'll never forget.\"\n\nAnda telah menyelesaikan praktikum 2 dengan sempurna. Selamat berjuang di praktikum selanjutnya. *kalo ada...\n~ Sister'22\n\n"; // idb
_DWORD array_3149[9] = { 3, 2, 6, 5, 9, 1, 8, 4, 7 }; // weak
int dword_62FC = 1869771333; // weak
int dword_6374 = 1869771333; // weak
int (*_frame_dummy_init_array_entry[2])() = { &frame_dummy, &_do_global_dtors_aux }; // weak
Elf32_Dyn *GLOBAL_OFFSET_TABLE_ = &DYNAMIC; // weak
char userid[9] = "13525119"; // weak
char bomb_id[2] = "w"; // weak
char _TMC_END__; // weak
int num_input_strings; // weak
FILE *infile; // idb
char input_strings[80000]; // weak
// extern struct _IO_FILE *stderr;
// extern struct _IO_FILE *stdin;
// extern struct _IO_FILE *stdout;
// extern _UNKNOWN _gmon_start__; weak


//----- (00001000) --------------------------------------------------------
// Alternative name is '_init'
void *init_proc()
{
  void *result; // eax

  result = &_gmon_start__;
  if ( &_gmon_start__ )
    return (void *)((int (*)(void))_gmon_start__)();
  return result;
}

//----- (00001030) --------------------------------------------------------
void sub_1030()
{
  __asm { jmp     dword ptr [ebx+8] }
}
// 1036: unbalanced stack, ignored a potential tail call

//----- (00001040) --------------------------------------------------------
void sub_1040()
{
  sub_1030();
}

//----- (00001050) --------------------------------------------------------
void sub_1050()
{
  sub_1030();
}

//----- (00001060) --------------------------------------------------------
void sub_1060()
{
  sub_1030();
}

//----- (00001070) --------------------------------------------------------
void sub_1070()
{
  sub_1030();
}

//----- (00001080) --------------------------------------------------------
void sub_1080()
{
  sub_1030();
}

//----- (00001090) --------------------------------------------------------
void sub_1090()
{
  sub_1030();
}

//----- (000010A0) --------------------------------------------------------
void sub_10A0()
{
  sub_1030();
}

//----- (000010B0) --------------------------------------------------------
void sub_10B0()
{
  sub_1030();
}

//----- (000010C0) --------------------------------------------------------
void sub_10C0()
{
  sub_1030();
}

//----- (000010D0) --------------------------------------------------------
void sub_10D0()
{
  sub_1030();
}

//----- (000010E0) --------------------------------------------------------
void sub_10E0()
{
  sub_1030();
}

//----- (000010F0) --------------------------------------------------------
void sub_10F0()
{
  sub_1030();
}

//----- (00001100) --------------------------------------------------------
void sub_1100()
{
  sub_1030();
}

//----- (00001110) --------------------------------------------------------
void sub_1110()
{
  sub_1030();
}

//----- (00001120) --------------------------------------------------------
void sub_1120()
{
  sub_1030();
}

//----- (00001130) --------------------------------------------------------
void sub_1130()
{
  sub_1030();
}

//----- (00001140) --------------------------------------------------------
void sub_1140()
{
  sub_1030();
}

//----- (00001150) --------------------------------------------------------
void sub_1150()
{
  sub_1030();
}

//----- (00001160) --------------------------------------------------------
void sub_1160()
{
  sub_1030();
}

//----- (00001170) --------------------------------------------------------
void sub_1170()
{
  sub_1030();
}

//----- (00001180) --------------------------------------------------------
void sub_1180()
{
  sub_1030();
}

//----- (00001190) --------------------------------------------------------
void sub_1190()
{
  sub_1030();
}

//----- (000011A0) --------------------------------------------------------
void sub_11A0()
{
  sub_1030();
}

//----- (000011B0) --------------------------------------------------------
void sub_11B0()
{
  sub_1030();
}

//----- (000011C0) --------------------------------------------------------
void sub_11C0()
{
  sub_1030();
}

//----- (000011D0) --------------------------------------------------------
void sub_11D0()
{
  sub_1030();
}

//----- (000011E0) --------------------------------------------------------
int __usercall sub_11E0@<eax>(int a1@<ebx>)
{
  return (*(int (**)(void))(a1 + 128))();
}

//----- (00001390) --------------------------------------------------------
// positive sp value has been detected, the output may be wrong!
void __usercall __noreturn start(int a1@<eax>, void (*a2)()@<edx>)
{
  int v2; // esi
  int v3; // [esp-4h] [ebp-4h] BYREF
  char *retaddr; // [esp+0h] [ebp+0h] BYREF

  v2 = v3;
  v3 = a1;
  __libc_start_main(
    (int (*)(int, char **, char **))main,
    v2,
    &retaddr,
    (void (*)())_libc_csu_init,
    _libc_csu_fini,
    a2,
    &v3);
  __halt();
}
// 1397: positive sp value 4 has been found

//----- (000013C6) --------------------------------------------------------
void sub_13C6()
{
  ;
}

//----- (000013D0) --------------------------------------------------------
void _x86_get_pc_thunk_bx()
{
  ;
}

//----- (000013E0) --------------------------------------------------------
char *deregister_tm_clones()
{
  return &_TMC_END__;
}
// 13E0: could not find valid save-restore pair for ebp
// 9640: using guessed type char _TMC_END__;

//----- (00001420) --------------------------------------------------------
int register_tm_clones()
{
  return 0;
}
// 1420: could not find valid save-restore pair for ebp

//----- (00001470) --------------------------------------------------------
char *_do_global_dtors_aux()
{
  char *result; // eax

  if ( !_TMC_END__ )
  {
    if ( &_cxa_finalize )
      sub_11E0((int)&GLOBAL_OFFSET_TABLE_);
    result = deregister_tm_clones();
    _TMC_END__ = 1;
  }
  return result;
}
// 8F64: using guessed type Elf32_Dyn *GLOBAL_OFFSET_TABLE_;
// 9640: using guessed type char _TMC_END__;

//----- (000014C0) --------------------------------------------------------
int frame_dummy()
{
  return register_tm_clones();
}

//----- (000014C9) --------------------------------------------------------
void _x86_get_pc_thunk_dx()
{
  ;
}

//----- (000014CD) --------------------------------------------------------
int __cdecl main(int argc, const char **argv, const char **envp)
{
  const char *line; // eax
  char *v4; // eax
  const char *v5; // eax
  const char *v6; // eax
  const char *v7; // eax
  const char *v8; // eax
  const char *v9; // eax
  const char *v10; // eax
  unsigned __int8 *v11; // eax
  char *v12; // eax

  puts("Starting...");
  if ( argc == 1 )
  {
    infile = stdin;
  }
  else
  {
    if ( argc != 2 )
    {
      __printf_chk(1, "Usage: %s [<input_file>]\n");
      exit(8);
    }
    infile = fopen(argv[1], "r");
    if ( !infile )
    {
      __printf_chk(1, "%s: Error: Couldn't open %s\n");
      exit(8);
    }
  }
  start_game();
  __printf_chk(1, &unk_4050);
  line = read_line();
  shigatsu_wa_kimi_no_uso(line);
  stage_completed();
  __printf_chk(
    1,
    "\n"
    "Phase 1: THE RECOGNITION - Memories Unlocked\n"
    "\"Yes... yes! You remember. The bond is still there. It's still alive.\"\n"
    "\"Then hear us now. We need you more than ever.\"\n"
    "\n"
    "The first gate opens before you.\n"
    "Ancient symbols glow with ethereal light.\n"
    "\n"
    "\"To pass through, you must prove your strength of mind.\"\n"
    "\"Solve the equation that binds reality itself.\"\n"
    "\n"
    "> ");
  v4 = (char *)read_line();
  gurren_lagann(v4);
  stage_completed();
  __printf_chk(
    1,
    "\n"
    "Phase 2: THE EQUATION - Logic Proven\n"
    "The gate trembles and begins to crack open...\n"
    "\"Your mind still burns with potential. Good. You'll need it.\"\n"
    "\n"
    "Deep underground, you find an ancient chamber.\n"
    "Strange runes line the walls, shifting and changing.\n"
    "A voice echoes from the darkness...\n"
    "\n"
    "\"This is the Chamber of Secrets. Decoding is the only way forward.\"\n"
    "\"Transform our hidden message. Make it whole again.\"\n"
    "\n"
    "> ");
  v5 = read_line();
  cruel_angel_thesis((int)v5);
  stage_completed();
  __printf_chk(
    1,
    "\n"
    "Phase 3: THE CIPHER - Secrets Revealed\n"
    "The runes suddenly align, revealing a passage of blinding light...\n"
    "\"You're not just remembering us. You're BECOMING us.\"\n"
    "\n"
    "An encrypted signal breaks through the noise.\n"
    "Layers upon layers of obfuscation hide something precious.\n"
    "\"We locked away something important in here. Can you retrieve it?\"\n"
    "\"Unravel the encoding. Find what we hid for you.\"\n"
    "\n"
    "> ");
  v6 = read_line();
  one_piece((int)v6);
  stage_completed();
  __printf_chk(
    1,
    "\n"
    "Phase 4: THE MESSAGE - Truth Extracted\n"
    "A burst of clarity. A fragment of something whole. Something you thought was lost.\n"
    "\"This is just the beginning. There's so much more you need to understand.\"\n"
    "\n"
    "You stand before a vast crystalline structure.\n"
    "It dances with impossible geometry, shifting between dimensions.\n"
    "\"This is the Geometric Heart. It requires perfect synchronization.\"\n"
    "\"Dance with us through its patterns. Show us you move as one.\"\n"
    "\n"
    "> ");
  v7 = read_line();
  Geometric_Dance((int)v7);
  stage_completed();
  __printf_chk(
    1,
    "\n"
    "Phase 5: THE GEOMETRIC DANCE - Harmony Achieved\n"
    "The crystal resonates with your presence, bathing everything in golden light...\n"
    "You feel connected. Truly connected for the first time in ages.\n"
    "\n"
    "The environment shifts. You're crossing a field of endless possibilities.\n"
    "Each step carries weight. Each choice matters.\n"
    "\"We've marked a path for you. Can you find it among the infinite noise?\"\n"
    "\"Track our signal. Cross the field to reach us.\"\n"
    "\n"
    "> ");
  v8 = read_line();
  crossing_field(v8);
  stage_completed();
  __printf_chk(
    1,
    "\n"
    "Phase 6: CROSSING THE FIELD - Path Found\n"
    "The chaos clears. A singular path emerges before you.\n"
    "You're getting closer. You can feel it now.\n"
    "\n"
    "The next trial is more complex. More intricate.\n"
    "\"We're asking more of you now because... because you're almost here.\"\n"
    "\"This requires layers of understanding. Functions within functions.\"\n"
    "\"Show us the depth of your wisdom.\"\n"
    "\n"
    "> ");
  v9 = read_line();
  renai_circulation((int)v9);
  stage_completed();
  puts(
    "\n"
    "Phase 7: LAYERS DEEP - Understanding Achieved\n"
    "Knowledge floods through you like a second awakening.\n"
    "You're not just solving puzzles anymore. You're reading their minds.\n");
  sleep(1u);
  puts(byte_4E48);
  sleep(1u);
  __printf_chk(
    1,
    "The penultimate chamber materializes before you.\n"
    "Something ancient and sacred waits within.\n"
    "\"This is where our hearts have been locked away.\"\n"
    "\"We encrypted them to keep them safe. To keep them waiting for YOU.\"\n"
    "\"Find the key. Unlock what we've been protecting.\"\n"
    "\n"
    "> ");
  v10 = read_line();
  kira_game(v10);
  stage_completed();
  __printf_chk(
    1,
    "\n"
    "Bonus Phase 1: HEART'S ENCRYPTION - Love Unlocked\n"
    "Something warm floods through you. Tears stream down your face.\n"
    "These aren't puzzles. These are pieces of them. Pieces of your story together.\n"
    "\"Incredible. You went deeper. You actually went deeper for us.\"\n"
    "\"That means more than you know.\"\n"
    "\n"
    "You stand before the Nexus of Balance.\n"
    "An infinite grid of possibilities, waiting to be arranged.\n"
    "\"The universe demands balance. So do we.\"\n"
    "\"Create the perfect square. Bring harmony to chaos. Bring us back to you.\"\n"
    "\n"
    "> ");
  v11 = (unsigned __int8 *)read_line();
  Shougaizettaisouaisengen(v11);
  stage_completed();
  __printf_chk(
    1,
    "\n"
    "Bonus Phase 2: PERFECT BALANCE - Harmony Restored\n"
    "Reality stabilizes. The dimensions align.\n"
    "You can see them now. Not clearly, but you know they're there.\n"
    "\"You're doing things we thought impossible. Keep going. One more.\"\n"
    "\"This last one... it's special. It's everything.\"\n"
    "\n"
    "The final gate. The last boundary.\n"
    "A tree of infinite branches stretches before you.\n"
    "At its roots: your past. At its crown: your future.\n"
    "\"This is it. The moment of truth.\"\n"
    "\"Navigate through the branches of fate. Find the answer at the heart of everything.\"\n"
    "\"This is where we've been waiting for you all along.\"\n"
    "\n"
    "> ");
  v12 = (char *)read_line();
  Ruler_Count_Zero_2(v12);
  stage_completed();
  puts(
    "\n"
    "Bonus Phase 3: THE TREE OF DESTINY - Truth Found\n"
    "The branches dissolve into light, and everything becomes clear.\n"
    "\"You did it. You came all the way. Through everything. For us.\"\n"
    "\"There's nothing left to prove. You are the legend. The one we've been waiting for.\"\n");
  sleep(2u);
  puts(byte_59AC);
  sleep(2u);
  puts(
    "The final transmission arrives...\n"
    "\n"
    "\"You did it. Against all odds, against time itself, you did it.\"\n"
    "\"You navigated through our pain, our secrets, our hearts.\"\n"
    "\"You reminded us that no matter how far we drift, we can always find our way back.\"\n"
    "\n"
    "\"This wasn't just about solving problems, was it?\"\n"
    "\"This was about remembering. Reconnecting. Coming home.\"\n");
  sleep(2u);
  puts(aThankYouThankY);
  return 0;
}

//----- (00001795) --------------------------------------------------------
bool __cdecl shigatsu_wa_kimi_no_uso(const char *a1)
{
  bool v1; // zf
  bool result; // al

  v1 = strcmp(a1, "frulli_frulla") == 0;
  result = !v1;
  if ( !v1 )
    trap();
  return result;
}

//----- (000017CC) --------------------------------------------------------
int __cdecl gurren_lagann(char *nptr)
{
  int result; // eax

  result = strtol(nptr, nullptr, 10);
  if ( result != 726 )
    trap();
  return result;
}

//----- (00001802) --------------------------------------------------------
unsigned int __cdecl cruel_angel_thesis(int a1)
{
  int i; // esi
  char v3[8]; // [esp+4h] [ebp-28h] BYREF
  unsigned int v4; // [esp+Ch] [ebp-20h]

  v4 = __readgsdword(0x14u);
  strcpy(v3, "ZANKOKU");
  for ( i = 0; i != 7; ++i )
  {
    if ( (*(char *)(a1 + i) - 49) % 26 + 65 != v3[i] )
      trap();
  }
  return __readgsdword(0x14u) ^ v4;
}

//----- (00001895) --------------------------------------------------------
unsigned int __cdecl one_piece(int a1)
{
  int i; // esi
  char v3[9]; // [esp+3h] [ebp-29h] BYREF
  unsigned int v4; // [esp+Ch] [ebp-20h]

  v4 = __readgsdword(0x14u);
  strcpy(v3, "onepiece");
  for ( i = 0; i != 8; ++i )
  {
    if ( v3[i] != (*(_BYTE *)(a1 + i) ^ 0x21) )
      trap();
  }
  return __readgsdword(0x14u) ^ v4;
}

//----- (00001911) --------------------------------------------------------
unsigned int __cdecl Geometric_Dance(int a1)
{
  int v2; // eax
  int v3; // edx
  int v4; // [esp+10h] [ebp-24h] BYREF
  int v5; // [esp+14h] [ebp-20h] BYREF
  int v6; // [esp+18h] [ebp-1Ch] BYREF
  _DWORD v7[2]; // [esp+1Ch] [ebp-18h] BYREF
  unsigned int v8; // [esp+24h] [ebp-10h]

  v8 = __readgsdword(0x14u);
  if ( __isoc99_sscanf(a1, "%d %d %d %d", &v4, &v5, &v6, v7) != 4 )
    trap();
  v7[1] = 564;
  if ( v4 != 564 )
    trap();
  if ( english_or_spanish(564) != v5
    || (v2 = english_or_spanish(v5), v2 != v6)
    || (v3 = english_or_spanish(v6), v3 != v7[0]) )
  {
    trap();
  }
  return __readgsdword(0x14u) ^ v8;
}
// 12E0: using guessed type int __isoc99_sscanf(_DWORD, const char *, ...);

//----- (000019EA) --------------------------------------------------------
unsigned int __cdecl crossing_field(const char *a1)
{
  int v1; // esi
  unsigned __int8 v2; // al
  char v3; // al
  char v6[7]; // [esp+5h] [ebp-27h] BYREF
  unsigned int v7; // [esp+Ch] [ebp-20h]

  v7 = __readgsdword(0x14u);
  strcpy(v6, "topoki");
  if ( ~(strlen(a1) + 1) != -8 )
    trap();
  v1 = 1;
  while ( 1 )
  {
    v3 = a1[v1 - 1];
    switch ( v1 )
    {
      case 1:
        v2 = v3 - 3;
        goto LABEL_5;
      case 2:
        v2 = v3 + 4;
        goto LABEL_5;
      case 3:
        v2 = v3 - 2;
        goto LABEL_5;
      case 4:
        v2 = v3 - 1;
        goto LABEL_5;
      case 5:
        v2 = v3 + 4;
LABEL_5:
        if ( v2 != v6[v1 - 1] )
          goto LABEL_6;
        ++v1;
        break;
      case 6:
        if ( (unsigned __int8)(v3 + 5) != v6[5] )
LABEL_6:
          trap();
        return __readgsdword(0x14u) ^ v7;
      default:
        trap();
    }
  }
}

//----- (00001AC2) --------------------------------------------------------
unsigned int __cdecl renai_circulation(int a1)
{
  int v2; // [esp+4h] [ebp-18h] BYREF
  int v3; // [esp+8h] [ebp-14h] BYREF
  unsigned int v4; // [esp+Ch] [ebp-10h]

  v4 = __readgsdword(0x14u);
  __isoc99_sscanf(a1, "%d %d", &v2, &v3);
  if ( karaage(v2) != 36 )
    trap();
  if ( ramen(v2, v3) != 589824 )
    trap();
  return __readgsdword(0x14u) ^ v4;
}
// 12E0: using guessed type int __isoc99_sscanf(_DWORD, const char *, ...);

//----- (00001B4E) --------------------------------------------------------
unsigned int __cdecl kira_game(const char *a1)
{
  int i; // esi
  _DWORD v3[2]; // [esp+2h] [ebp-2Ah] BYREF
  unsigned int v4; // [esp+Ch] [ebp-20h]

  v4 = __readgsdword(0x14u);
  qmemcpy(v3, "IX9|c|Nf", sizeof(v3));
  if ( ~(strlen(a1) + 1) != -10 )
    trap();
  for ( i = 0; i != 8; ++i )
  {
    if ( (a1[i] ^ (unsigned __int8)(2 * i + 5)) != *((_BYTE *)v3 + i) )
      trap();
  }
  return __readgsdword(0x14u) ^ v4;
}

//----- (00001BDA) --------------------------------------------------------
int __cdecl Shougaizettaisouaisengen(unsigned __int8 *a1)
{
  int v1; // esi
  int i; // ebx
  unsigned __int8 *v3; // esi
  char *v4; // ebx
  int v5; // edi
  int v6; // ebp
  int result; // eax
  int j; // [esp+18h] [ebp-30h]
  char *v9; // [esp+1Ch] [ebp-2Ch]
  int v10; // [esp+20h] [ebp-28h]

  if ( string_length(a1) != 9 )
    trap();
  v1 = 0;
  v10 = 0;
  for ( i = 0; i != 3; ++i )
  {
    v10 += array_3149[((char)a1[4 * i] - 48) % 9];
    v1 += array_3149[((char)a1[2 * i + 2] - 48) % 9];
  }
  if ( v10 != v1 )
    trap();
  v9 = (char *)(a1 + 9);
  for ( j = 0; j != 3; ++j )
  {
    v3 = &a1[3 * j];
    v4 = (char *)&a1[j];
    v5 = 0;
    v6 = 0;
    do
    {
      v6 += array_3149[((char)*v3 - 48) % 9];
      v5 += array_3149[(*v4 - 48) % 9];
      ++v3;
      v4 += 3;
    }
    while ( v4 != v9 );
    if ( v6 != v10 || v6 != v5 )
      trap();
    ++v9;
  }
  result = *a1;
  if ( (_BYTE)result == a1[1]
    && (_BYTE)result == a1[2]
    && (_BYTE)result == a1[3]
    && (_BYTE)result == a1[4]
    && (_BYTE)result == a1[5]
    && (_BYTE)result == a1[6]
    && (_BYTE)result == a1[7]
    && (_BYTE)result == a1[8] )
  {
    trap();
  }
  return result;
}
// 6000: using guessed type _DWORD array_3149[9];

//----- (00001DA0) --------------------------------------------------------
unsigned int __cdecl Ruler_Count_Zero_2(_BYTE *a1)
{
  _BYTE *v1; // esi
  _DWORD *v2; // edi
  _DWORD v4[3]; // [esp+8h] [ebp-64h] BYREF
  _DWORD v5[3]; // [esp+14h] [ebp-58h] BYREF
  _DWORD v6[3]; // [esp+20h] [ebp-4Ch] BYREF
  _DWORD v7[3]; // [esp+2Ch] [ebp-40h] BYREF
  _DWORD v8[3]; // [esp+38h] [ebp-34h] BYREF
  _DWORD v9[3]; // [esp+44h] [ebp-28h] BYREF
  _DWORD v10[3]; // [esp+50h] [ebp-1Ch] BYREF
  unsigned int v11; // [esp+5Ch] [ebp-10h]

  v1 = a1;
  v11 = __readgsdword(0x14u);
  v4[0] = 3;
  v4[1] = 0;
  v4[2] = 0;
  v5[0] = 7;
  v5[1] = 0;
  v5[2] = 0;
  v6[0] = 15;
  v6[1] = 0;
  v6[2] = 0;
  v7[0] = 67;
  v7[1] = 0;
  v7[2] = 0;
  v8[0] = 5;
  v8[1] = v4;
  v8[2] = v5;
  v9[0] = 20;
  v9[1] = v7;
  v9[2] = v6;
  v10[0] = 10;
  v10[1] = v8;
  v10[2] = v9;
  v2 = v10;
  if ( !*a1 )
    goto LABEL_2;
  do
  {
    if ( *v1 == 56 )
    {
      if ( !v2[1] )
        trap();
      v2 = (_DWORD *)v2[1];
    }
    else
    {
      if ( *v1 != 57 )
        trap();
      if ( !v2[2] )
        trap();
      v2 = (_DWORD *)v2[2];
    }
    ++v1;
  }
  while ( *v1 );
  if ( *v2 != 67 )
LABEL_2:
    trap();
  return __readgsdword(0x14u) ^ v11;
}

//----- (000023AB) --------------------------------------------------------
void *_x86_get_pc_thunk_ax()
{
  _UNKNOWN *retaddr; // [esp+0h] [ebp+0h]

  return retaddr;
}

//----- (000023AF) --------------------------------------------------------
void __noreturn sig_handler()
{
  puts("Eh??? You don't wanna do this anymore??? :((");
  sleep(1u);
  __printf_chk(1, "Well... ");
  fflush(stdout);
  sleep(1u);
  puts("Beware of [REDACTED]...");
  exit(16);
}
// 23AF: using guessed type void __noreturn sig_handler();

//----- (00002421) --------------------------------------------------------
void __cdecl __noreturn invalid_phase(int a1)
{
  __printf_chk(1, "Invalid phase%s\n");
  exit(8);
}

//----- (00002452) --------------------------------------------------------
int __cdecl string_length(_BYTE *a1)
{
  int result; // eax

  if ( !*a1 )
    return 0;
  result = 0;
  do
    ++result;
  while ( a1[result] );
  return result;
}

//----- (00002474) --------------------------------------------------------
int __cdecl strings_not_equal(char *a1, _BYTE *a2)
{
  char *v2; // ebx
  _BYTE *v3; // esi
  int v4; // edi
  int v5; // edx
  int result; // eax
  char v7; // al

  v2 = a1;
  v3 = a2;
  v4 = string_length(a1);
  v5 = string_length(a2);
  result = 1;
  if ( v4 == v5 )
  {
    v7 = *a1;
    if ( *a1 )
    {
      while ( *v3 == v7 )
      {
        ++v2;
        ++v3;
        v7 = *v2;
        if ( !*v2 )
          return 0;
      }
      return 1;
    }
    else
    {
      return 0;
    }
  }
  return result;
}

//----- (000024D0) --------------------------------------------------------
int __cdecl yakiniku(int a1, int a2)
{
  return a1 * a2;
}

//----- (000024DE) --------------------------------------------------------
int __cdecl sukiyaki(char a1)
{
  return 1 << a1;
}

//----- (000024EE) --------------------------------------------------------
int __cdecl karaage(int a1)
{
  int result; // eax

  result = 0;
  if ( a1 <= 99 )
    return karaage(a1 + 1) + 2;
  return result;
}

//----- (0000251B) --------------------------------------------------------
int __cdecl ramen(int a1, char a2)
{
  return karaage(a1) << a2;
}

//----- (00002535) --------------------------------------------------------
int __cdecl ruler_count_zero(int a1, int a2)
{
  _BOOL4 v3; // eax

  if ( a1 < a2 )
    return a2 + a1 != 89;
  v3 = 1;
  if ( a1 + a2 == 3 )
    v3 = a1 % (a2 + 1) != 0;
  return ruler_count_zero(a1 - v3 - 1, a2 + 2);
}

//----- (00002591) --------------------------------------------------------
int __cdecl english_or_spanish(int a1)
{
  return 3 * a1 + 1;
}

//----- (0000259E) --------------------------------------------------------
int __cdecl red_catastrophe(unsigned __int8 *a1, int a2)
{
  int result; // eax
  int v3; // ecx

  result = *a1;
  if ( (_BYTE)result )
  {
    v3 = 0;
    do
    {
      if ( (unsigned __int8)(result - 97) > 0x19u )
      {
        if ( (unsigned __int8)(result - 65) > 0x19u )
          *(_BYTE *)(a2 + v3) = result;
        else
          *(_BYTE *)(a2 + v3) = ((char)result - 52) % 26 + 65;
      }
      else
      {
        *(_BYTE *)(a2 + v3) = ((char)result - 84) % 26 + 97;
      }
      result = a1[++v3];
    }
    while ( (_BYTE)result );
  }
  else
  {
    v3 = 0;
  }
  *(_BYTE *)(a2 + v3) = 0;
  return result;
}

//----- (0000262F) --------------------------------------------------------
unsigned int start_game()
{
  char v1[12]; // [esp+1Ch] [ebp-2010h] BYREF
  unsigned int v2; // [esp+201Ch] [ebp-10h]

  v2 = __readgsdword(0x14u);
  signal(2, (__sighandler_t)sig_handler);
  if ( init_driver(v1) < 0 )
  {
    __printf_chk(1, "Initialization error:\n%s\n");
    exit(8);
  }
  return __readgsdword(0x14u) ^ v2;
}
// 23AF: using guessed type void __noreturn sig_handler();

//----- (000026C6) --------------------------------------------------------
void start_game_solve()
{
  ;
}

//----- (000026CB) --------------------------------------------------------
int __cdecl blank_line(char *a1)
{
  char v2; // si

  while ( 1 )
  {
    v2 = *a1;
    if ( !*a1 )
      break;
    ++a1;
    if ( ((*__ctype_b_loc())[v2] & 0x2000) == 0 )
      return 0;
  }
  return 1;
}

//----- (00002710) --------------------------------------------------------
char *skip()
{
  char *v0; // eax
  char *v1; // ebx

  do
  {
    v0 = fgets(
           (char *)&GLOBAL_OFFSET_TABLE_ + 400 * (_DWORD)*(&GLOBAL_OFFSET_TABLE_ + 440) + 1788,
           400,
           (FILE *)*(&GLOBAL_OFFSET_TABLE_ + 441));
    v1 = v0;
  }
  while ( v0 && blank_line(v0) );
  return v1;
}
// 8F64: using guessed type Elf32_Dyn *GLOBAL_OFFSET_TABLE_;

//----- (00002773) --------------------------------------------------------
// positive sp value has been detected, the output may be wrong!
unsigned int __cdecl send_msg()
{
  char v1; // [esp-4h] [ebp-4010h] BYREF
  char v2; // [esp+0h] [ebp-400Ch] BYREF
  int v3; // [esp+1000h] [ebp-300Ch] BYREF
  char v4[4068]; // [esp+1FFCh] [ebp-2010h] BYREF
  unsigned int v5; // [esp+3FFCh] [ebp-10h]

  while ( &v2 != (char *)(&v3 - 4096) )
    ;
  v5 = __readgsdword(0x14u);
  if ( strlen(&input_strings[400 * num_input_strings - 400]) + 100 > 0x2000 )
  {
    __printf_chk(1, "ERROR: Input string is too large.");
    exit(8);
  }
  __sprintf_chk(&v1, 1, 0x2000, "%d:%s:%d:%s", *(_DWORD *)bomb_id);
  if ( driver_post(userid, &v1, 0, v4) < 0 )
  {
    puts(v4);
    exit(0);
  }
  return __readgsdword(0x14u) ^ v5;
}
// 284B: positive sp value 3000 has been found
// 1380: using guessed type int __cdecl __sprintf_chk(_DWORD, _DWORD, _DWORD, _DWORD, _DWORD);
// 9644: using guessed type int num_input_strings;

//----- (0000288A) --------------------------------------------------------
void __noreturn trap()
{
  puts("\nYou acted carelessly. Something doesn't feel right.");
  puts("You stand helpless while a rush of anxiety swarms your mind..");
  putchar(46);
  fflush(stdout);
  sleep(1u);
  putchar(46);
  fflush(stdout);
  sleep(1u);
  puts(".");
  fflush(stdout);
  sleep(1u);
  puts("\"Ara-ara~ ngapain, Dek?\" You fainted.");
  fflush(stdout);
  send_msg();
  puts("The assistants have been notified of your incompetence.");
  exit(8);
}

//----- (00002964) --------------------------------------------------------
int __cdecl read_six_numbers(int a1, int a2)
{
  int result; // eax

  result = __isoc99_sscanf(a1, "%d %d %d %d %d %d", a2, a2 + 4, a2 + 8, a2 + 12, a2 + 16, a2 + 20);
  if ( result <= 5 )
    trap();
  return result;
}
// 12E0: using guessed type int __isoc99_sscanf(_DWORD, const char *, ...);

//----- (000029B2) --------------------------------------------------------
char *__cdecl read_n_numbers(char *s, int a2, int a3)
{
  char *v4; // eax
  int v5; // esi
  char *save_ptr; // [esp+18h] [ebp-28h] BYREF
  char delim[2]; // [esp+1Eh] [ebp-22h] BYREF
  unsigned int v9; // [esp+20h] [ebp-20h]

  v9 = __readgsdword(0x14u);
  strcpy(delim, " ");
  save_ptr = nullptr;
  v4 = strtok_r(s, delim, &save_ptr);
  if ( a2 > 0 )
  {
    if ( !v4 )
LABEL_8:
      trap();
    v5 = 0;
    while ( 1 )
    {
      if ( !__isoc99_sscanf(v4, "%d", a3) )
        trap();
      if ( a2 - 1 == v5 )
        break;
      v4 = strtok_r(nullptr, delim, &save_ptr);
      if ( a2 == ++v5 )
        break;
      a3 += 4;
      if ( !v4 )
        goto LABEL_8;
    }
  }
  return save_ptr;
}
// 12E0: using guessed type int __isoc99_sscanf(_DWORD, const char *, ...);

//----- (00002A8C) --------------------------------------------------------
int __cdecl input_to_integer(int a1, int a2)
{
  int result; // eax

  result = __isoc99_sscanf(a1, "%d", a2);
  if ( result <= 0 )
    trap();
  return result;
}
// 12E0: using guessed type int __isoc99_sscanf(_DWORD, const char *, ...);

//----- (00002AC4) --------------------------------------------------------
const char *read_line()
{
  int v0; // edx
  const char *v1; // esi
  unsigned int v2; // kr04_4
  int v4; // eax

  if ( !skip() )
  {
    if ( infile == stdin )
    {
      puts("Error: Premature EOF on stdin");
      exit(8);
    }
    if ( getenv("GRADE_BOMB") )
      exit(0);
    infile = stdin;
    if ( !skip() )
    {
      puts("Error: Premature EOF on stdin");
      exit(0);
    }
  }
  v0 = num_input_strings;
  v1 = &input_strings[400 * num_input_strings];
  v2 = strlen(v1) + 1;
  if ( (int)(v2 - 1) > 398 )
  {
    puts("Error: Input line too long");
    v4 = num_input_strings++;
    strcpy(&input_strings[400 * v4], "***truncated***");
    trap();
  }
  input_strings[400 * num_input_strings - 2 + v2] = 0;
  num_input_strings = v0 + 1;
  return v1;
}
// 9644: using guessed type int num_input_strings;

//----- (00002BF3) --------------------------------------------------------
int stage_completed()
{
  int result; // eax

  send_msg();
  result = __printf_chk(1, "============================ ");
  if ( num_input_strings == 6 )
  {
    puts("\nCongratulations on finishing the lab.");
    return puts("Your assistants have been notified.");
  }
  return result;
}
// 9644: using guessed type int num_input_strings;

//----- (00002C51) --------------------------------------------------------
void _x86_get_pc_thunk_bp()
{
  ;
}

//----- (00002C55) --------------------------------------------------------
void __noreturn sigalrm_handler()
{
  __fprintf_chk(stderr, 1, "Program timed out after %d seconds\n", 0);
  exit(1);
}
// 1330: using guessed type int __fprintf_chk(_DWORD, _DWORD, const char *, ...);
// 2C55: using guessed type void __noreturn sigalrm_handler();

//----- (00002C8C) --------------------------------------------------------
// positive sp value has been detected, the output may be wrong!
int __cdecl submitr(int a1, int a2, const char *a3, const char *a4, const char *a5, const char *a6, int a7)
{
  unsigned int v7; // kr0C_4
  const char *v8; // edi
  _BYTE *v9; // esi
  int v11; // eax
  int v12; // ecx
  FILE *v13; // eax
  FILE *v14; // esi
  unsigned int v15; // [esp-360h] [ebp-4370h]
  char v16[8]; // [esp-340h] [ebp-4350h] BYREF
  _BYTE v17[8192]; // [esp-338h] [ebp-4348h] BYREF
  char v18[4052]; // [esp+1CC8h] [ebp-2348h] BYREF
  unsigned int v19; // [esp+3FF0h] [ebp-20h]

  while ( &v17[824] != &v17[-11464] )
    ;
  v19 = __readgsdword(0x14u);
  v15 = strlen(a6) + 1;
  if ( strlen(a4) + 1 + strlen(a3) + 2 + strlen(a5) + 2 + 3 * v15 - 3 + 123 > 0x2000 )
  {
    strcpy((char *)a7, "Error: Result string too large. Increase SUBMITR_MAXBUF");
    close(0);
    return -1;
  }
  memset(v17, 0, sizeof(v17));
  v7 = strlen(a6) + 1;
  if ( v7 != 1 )
  {
    v8 = a6;
    v9 = v17;
    do
    {
      v11 = *(unsigned __int8 *)v8;
      if ( (unsigned __int8)(v11 - 42) > 0xFu )
      {
        if ( (_BYTE)v11 == 95 || (unsigned __int8)((v11 & 0xDF) - 65) <= 0x19u )
        {
LABEL_7:
          *v9++ = v11;
          goto LABEL_8;
        }
        if ( (_BYTE)v11 == 32 )
        {
          *v9++ = 43;
          goto LABEL_8;
        }
      }
      else
      {
        v12 = 65497;
        if ( _bittest(&v12, v11 - 42) )
          goto LABEL_7;
      }
      if ( (unsigned __int8)(v11 - 32) > 0x5Fu && (_BYTE)v11 != 9 )
      {
        *(_DWORD *)a7 = 1869771333;
        *(_DWORD *)(a7 + 63) = 3043941;
        qmemcpy(
          (void *)((a7 + 4) & 0xFFFFFFFC),
          (char *)&dword_6374 - (a7 - ((a7 + 4) & 0xFFFFFFFC)),
          4 * ((a7 - ((a7 + 4) & 0xFFFFFFFC) + 67) >> 2));
        close(0);
        return -1;
      }
      __sprintf_chk(v18, 1, 8, "%%%02X", (unsigned __int8)v11);
      *v9 = v18[0];
      v9[1] = v18[1];
      v9[2] = v18[2];
      v9 += 3;
LABEL_8:
      ++v8;
    }
    while ( v8 != &a6[v7 - 1] );
  }
  ((void (__cdecl *)(char *, int, int, int, const char *, int, int, _BYTE *, const char *))__snprintf_chk)(
    v18,
    9000,
    1,
    9000,
    "curl -s -o /tmp/resp.txt -w %%{http_code} \"http://%s:%d/api/submit?result=%s\" -H \"Authorization: Basic %s\"",
    a1,
    a2,
    v17,
    a5);
  v13 = popen(v18, "r");
  v14 = v13;
  if ( v13 )
  {
    if ( fgets(v16, 8, v13) )
    {
      pclose(v14);
      if ( strtol(v16, nullptr, 10) == 200 )
      {
        strcpy((char *)a7, "OK");
        return 0;
      }
      else
      {
        strcpy((char *)a7, "Error: http request failed.");
        return -1;
      }
    }
    else
    {
      pclose(v14);
      *(_DWORD *)a7 = 1869771333;
      *(_DWORD *)(a7 + 113) = 3043941;
      qmemcpy(
        (void *)((a7 + 4) & 0xFFFFFFFC),
        (char *)&dword_62FC - (a7 - ((a7 + 4) & 0xFFFFFFFC)),
        4 * ((a7 - ((a7 + 4) & 0xFFFFFFFC) + 117) >> 2));
      return -1;
    }
  }
  else
  {
    strcpy((char *)a7, "Error: failed to open cmd process.");
    return -1;
  }
}
// 3083: positive sp value 3000 has been found
// 2E36: conditional instruction was optimized away because al.1 is in (2A..39)
// 1380: using guessed type int __cdecl __sprintf_chk(_DWORD, _DWORD, _DWORD, _DWORD, _DWORD);
// 62FC: using guessed type int dword_62FC;
// 6374: using guessed type int dword_6374;

//----- (00003089) --------------------------------------------------------
unsigned int __cdecl init_timeout(int a1)
{
  unsigned int seconds; // esi
  unsigned int result; // eax

  seconds = a1;
  if ( a1 )
  {
    signal(14, (__sighandler_t)sigalrm_handler);
    if ( a1 < 0 )
      seconds = 0;
    return alarm(seconds);
  }
  return result;
}
// 2C55: using guessed type void __noreturn sigalrm_handler();

//----- (000030D3) --------------------------------------------------------
int __cdecl init_driver(char *a1)
{
  int v1; // eax
  int v2; // esi
  struct sockaddr addr; // [esp+1Ch] [ebp-20h] BYREF
  unsigned int v5; // [esp+2Ch] [ebp-10h]

  v5 = __readgsdword(0x14u);
  __printf_chk(1, "Connecting to %s...\n");
  signal(13, (__sighandler_t)((char *)&dword_0 + 1));
  signal(29, (__sighandler_t)((char *)&dword_0 + 1));
  signal(29, (__sighandler_t)((char *)&dword_0 + 1));
  puts("Creating socket...");
  v1 = socket(2, 1, 0);
  if ( v1 < 0 )
  {
    strcpy(a1, "Error: Client unable to create socket");
    return -1;
  }
  else
  {
    v2 = v1;
    memset(&addr.sa_data[3], 0, 11);
    addr.sa_family = 2;
    strcpy(addr.sa_data, "'$");
    if ( inet_pton(2, "51.75.19.81", &addr.sa_data[2]) <= 0 )
    {
      strcpy(a1, "Error: invalid IPv4 address");
      close(v2);
      return -1;
    }
    else
    {
      puts("Connecting to server...");
      if ( connect(v2, &addr, 0x10u) < 0 )
      {
        __sprintf_chk(a1, 1, -1, "Error: Unable to connect to server %s", "51.75.19.81");
        close(v2);
        return -1;
      }
      else
      {
        puts("Connected to server...");
        close(v2);
        strcpy(a1, "OK");
        return 0;
      }
    }
  }
}
// 0: using guessed type int dword_0;
// 1380: using guessed type int __cdecl __sprintf_chk(_DWORD, _DWORD, _DWORD, _DWORD, _DWORD);

//----- (000032D2) --------------------------------------------------------
int __cdecl driver_post(const char *a1, const char *a2, int a3, char *a4)
{
  int result; // eax

  result = a3;
  if ( a3 )
  {
    __printf_chk(1, "\nAUTORESULT_STRING=%s\n");
    strcpy(a4, "OK");
    return 0;
  }
  else if ( a1 && *a1 )
  {
    return submitr((int)"51.75.19.81", 10020, "csapp", a1, "MTM1MjUxMTk6ZWxlY3RyaWNhbmdlbA==", a2, (int)a4);
  }
  else
  {
    strcpy(a4, "OK");
  }
  return result;
}

//----- (00003370) --------------------------------------------------------
int _libc_csu_init()
{
  int i; // esi
  int result; // eax

  init_proc();
  for ( i = 0; i != 1; ++i )
    result = _frame_dummy_init_array_entry[i]();
  return result;
}
// 8E64: using guessed type int (*_frame_dummy_init_array_entry[2])();

//----- (000033E0) --------------------------------------------------------
void _libc_csu_fini()
{
  ;
}

//----- (00003408) --------------------------------------------------------
// Alternative name is '_fini'
void term_proc()
{
  ;
}

// nfuncs=134 queued=80 decompiled=80 lumina nreq=0 worse=0 better=0
// ALL OK, 80 function(s) have been successfully decompiled
